### ISSUE TITLE
Tracking Issue(#2) : 権限管理

### ISSUE THREAD

**Issue by kawaemon** [approvers/RFCs#3]
ここではマージされたRFC「権限管理」についてのやるべきことの進捗を管理します。

---

> (上の水平線以降は Todo を管理するために @loxyenK が編集しています。)

## Todo

- [x] サーバーテンプレートの作成 ( §4.2 )
- [x] 操作を行う人に対する、「全知全能の神」より Discord 上で上位となるロールの一時的な付与
- [x] ロールの作成 ( §3 )
- [x] ロールの付与設定の削除
  - 一部のユーザに対し、自動的にロールが付与されているため、それを削除し、以降の操作を行ったときに一切の影響が発生しないようにします。
  - 「にゃーん」に対しては行いません。 
- [x] ロールの権限設定 ( §4 )
  - [x] 「全知全能の神」( §4.1 )
  - [x] 「限界治安部隊」( §4.2 )
  - [x] 「にゃーん」( §4.3 )
- [x] ロールの設定確認 ( §4 )
- [x] ロールの付与 ( §3 )
  - [x] 「全知全能の神」( §4.1 )
  - [x] 「限界治安部隊」( §4.2 )
  - 「にゃーん」については、現状を維持します。
- [x] 一時的なロールの削除

**Comment by loxygenK** [comment]
現時点でロールの設定が完了しています。今は他の全知全能の神を持つユーザからの、限界治安部隊のメンバーについての承認を待っています。

**Comment by loxygenK** [comment]
限界治安部隊のメンバーが確定しました。

**Comment by loxygenK** [comment]
全ての Todo が完了しました :tada:
